/*Written by Josh Kennerly and Justin Schulz*/
CREATE SCHEMA IF NOT EXISTS Pizzeria;
USE Pizzeria;

CREATE TABLE IF NOT EXISTS TOPPINGS(
    TOPPING_ID VARCHAR(255) NOT NULL UNIQUE AUTO_INCREMENT,
    TOPPING_PRICE FLOAT NOT NULL,
    TOPPING_COST FLOAT NOT NULL,
    TOPPING_INVENTORY INT NOT NULL,
    TOPPING_SMALL FLOAT NOT NULL,
    TOPPING_MED FLOAT NOT NULL,
    TOPPING_LARGE FLOAT NOT NULL,
    TOPPING_XL FLOAT NOT NULL,
    PRIMARY KEY (TOPPING_ID)
);

CREATE TABLE IF NOT EXISTS PIZZAS(
    PIZZA_ID INT NOT NULL UNIQUE AUTO_INCREMENT,
    PIZZA_SIZE VARCHAR(255) NOT NULL,
    PIZZA_CRUST VARCHAR(255) NOT NULL,
    ORDER_ID INT NOT NULL,
    PIZZA_COST FLOAT NOT NULL,
    PIZZA_PRICE FLOAT NOT NULL,
    PIZZA_DATE DATE NOT NULL,
    PIZZA_COMPLETE BOOL NOT NULL,
    PRIMARY KEY (PIZZA_ID),
    FOREIGN KEY (PIZZA_SIZE, PIZZA_CRUST) REFERENCES BASE_PRICE(PIZZA_SIZE, PIZZA_CRUST),
    FOREIGN KEY (ORDER_ID) REFERENCES ORDERS(ORDER_ID)
);

CREATE TABLE IF NOT EXISTS ORDERS(
    ORDER_ID INT NOT NULL UNIQUE AUTO_INCREMENT,
    CUSTOMER_ID INT,
    ORDER_TIME DATETIME NOT NULL,
    ORDER_PRICE FLOAT NOT NULL,
    ORDER_COST FLOAT NOT NULL,
    ORDER_COMPLETE INT NOT NULL,
    ORDER_PICKEDUP INT,
    ORDER_TABLE_NUM INT,
    ORDER_TYPE VARCHAR(255) NOT NULL,
    PRIMARY KEY (ORDER_ID),
    FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMER(CUSTOMER_ID)
);

CREATE TABLE IF NOT EXISTS CUSTOMER(
    CUSTOMER_ID INT NOT NULL UNIQUE AUTO_INCREMENT,
    CUSTOMER_FIRSTNAME VARCHAR(255) NOT NULL,
    CUSTOMER_LASTNAME VARCHAR(255) NOT NULL,
    CUSTOMER_PHONE VARCHAR(255) NOT NULL UNIQUE,
    CUSTOMER_ADDRESS VARCHAR(255),
    PRIMARY KEY (CUSTOMER_ID)
);

CREATE TABLE IF NOT EXISTS DISCOUNTS(
    DISCOUNT_ID VARCHAR(255) NOT NULL,
    DISCOUNT_PERCENT FLOAT NOT NULL,
    DISCOUNT_CASH FLOAT NOT NULL,
    PRIMARY KEY (DISCOUNT_ID)
);

CREATE TABLE IF NOT EXISTS BASE_PRICE(
    PIZZA_CRUST VARCHAR(255) NOT NULL,
    PIZZA_SIZE VARCHAR(255) NOT NULL,
    PIZZA_COST FLOAT NOT NULL,
    PIZZA_PRICE FLOAT NOT NULL,
    PRIMARY KEY (PIZZA_CRUST, PIZZA_SIZE)
);

CREATE TABLE IF NOT EXISTS TOTAL_TOPS(
    PIZZA_ID INT NOT NULL,
    TOPPING_ID VARCHAR(255) NOT NULL,
    TOPPING_EXTRA BOOL NOT NULL,
    PRIMARY KEY (PIZZA_ID, TOPPING_ID),
    FOREIGN KEY (PIZZA_ID) REFERENCES PIZZAS(PIZZA_ID),
    FOREIGN KEY (TOPPING_ID) REFERENCES TOPPINGS(TOPPING_ID)  
);

CREATE TABLE IF NOT EXISTS DISCOUNT_PIZZA(
    PIZZA_ID INT NOT NULL,
    DISCOUNT_ID VARCHAR(255) NOT NULL,
    PRIMARY KEY (PIZZA_ID, DISCOUNT_ID),
    FOREIGN KEY (PIZZA_ID) REFERENCES PIZZAS(PIZZA_ID),
    FOREIGN KEY (DISCOUNT_ID) REFERENCES DISCOUNTS(DISCOUNT_ID)
);

CREATE TABLE IF NOT EXISTS DISCOUNT_ORDER(
    ORDER_ID INT NOT NULL,
    DISCOUNT_ID VARCHAR(255) NOT NULL,
    PRIMARY KEY (ORDER_ID, DISCOUNT_ID),
    FOREIGN KEY (ORDER_ID) REFERENCES ORDERS(ORDER_ID),
    FOREIGN KEY (DISCOUNT_ID) REFERENCES DISCOUNTS(DISCOUNT_ID)
);
