/*Written by Josh Kennerly and Justin Schulz*/

use Pizzeria;

DROP TABLE IF EXISTS TOPPINGS;

DROP TABLE IF EXISTS PIZZAS;

DROP TABLE IF EXISTS ORDERS;

DROP TABLE IF EXISTS CUSTOMER;

DROP TABLE IF EXISTS DISCOUNTS;

DROP TABLE IF EXISTS BASE_PRICE;

DROP TABLE IF EXISTS TOTAL_TOPS;

DROP TABLE IF EXISTS DISCOUNT_PIZZA;

DROP TABLE IF EXISTS DISCOUNT_ORDER;

DROP SCHEMA IF EXISTS Pizzeria;
