use Pizzeria;

CREATE TABLE TOPPINGS(
TOPPING_ID INT UNIQUE NOT NULL,
TOPPING_NAME VARCHAR(255) NOT NULL,
TOPPING_PRICE_CUST FLOAT NOT NULL,
TOPPING_PRICE_BIZ FLOAT NOT NULL,
TOPPING_INV_CURR FLOAT NOT NULL,
TOPPING_DOUBLE INT NOT NULL,
FOREIGN KEY (PIZZA_SIZE)
	REFERENCES PIZZAS(PIZZA_SIZE),
SMALL FLOAT NOT NULL,
MEDIUM FLOAT NOT NULL,
LARGE FLOAT NOT NULL,
PRIMARY KEY (TOPPING_ID)
);

CREATE TABLE PIZZAS(
PIZZA_ID INT UNIQUE NOT NULL,
PIZZA_SIZE VARCHAR(255) NOT NULL,
PIZZA_CRUST VARCHAR(255) NOT NULL,
FOREIGN KEY (TOPPING_ID)
	REFERENCES TOPPINGS(TOPPING_ID),
FOREIGN KEY (PIZZA_COST)
	REFERENCES COST(PIZZA_COST),
PRIMARY KEY (PIZZA_ID)
);

CREATE TABLE ORDERS(
ORDER_ID INT UNIQUE NOT NULL,
ORDER_DATE DATE,
ORDER_TYPE VARCHAR(255),
FOREIGN KEY (CUSTOMER_ID)
	REFERENCES CUSTOMER(CUSTOMER_ID),
FOREIGN KEY (PIZZA_COST)
	REFERENCES COST(PIZZA_COST),
PRIMARY KEY (ORDER_ID)
);

CREATE TABLE CUSTOMER(
CUSTOMER_ID INT UNIQUE NOT NULL,
CUSTOMER_NAME VARCHAR(255),
CUSTOMER_PHONE VARCHAR(255),
CUSTOMER_ADDRESS VARCHAR(255),
PRIMARY KEY (CUSTOMER_ID)
);

CREATE TABLE DINE_IN(
FOREIGN KEY (ORDER_TYPE)
	REFERENCES ORDERS(ORDER_TYPE),
FOREIGN KEY (CUSTOMER_NAME)
	REFERENCES CUSTOMER(CUSTOMER_NAME),    
TABLE_NUM INT,
PRIMARY KEY ORDER_TYPE(CUSTOMER_NAME, ORDER_TYPE)
);

CREATE TABLE TAKEOUT(
FOREIGN KEY (ORDER_TYPE)
	REFERENCES ORDERS(ORDER_TYPE),
FOREIGN KEY (CUSTOMER_NAME)
	REFERENCES CUSTOMER(CUSTOMER_NAME),
FOREIGN KEY (CUSTOMER_PHONE)
	REFERENCES CUSTOMER(CUSTOMER_PHONE),
PRIMARY KEY ORDER_TYPE(CUSTOMER_NAME, CUSTOMER_PHONE)
);

CREATE TABLE DELIVERY(
FOREIGN KEY (ORDER_TYPE)
	REFERENCES ORDERS(ORDER_TYPE),
FOREIGN KEY (CUSTOMER_ID)
	REFERENCES CUSTOMER(CUSTOMER_ID),
PRIMARY KEY ORDER_TYPE(ORDER_TYPE, CUSTOMER_ID)
);

CREATE TABLE DISCOUNTS(
DISCOUNT_ID INT UNIQUE NOT NULL,
DISCOUNT_NAME VARCHAR(255),
DISCOUNT_PERCENT FLOAT NOT NULL,
DISCOUNT_CASH FLOAT NOT NULL
);

CREATE TABLE BASE_PRICE(
PSIZE_CRUST FLOAT NOT NULL,
FOREIGN KEY (PIZZA_CRUST)
	REFERENCES PIZZA(PIZZA_CRUST),
FOREIGN KEY (PIZZA_SIZE)
	REFERENCES PIZZA(PIZZA_SIZE),
PIZZA_COST FLOAT NOT NULL,
PIZZA_PRICE FLOAT NOT NULL,
PRIMARY KEY PSIZE_CRUST(PIZZA_CRUST, PIZZA_SIZE)
);
