CREATE TABLE TOPPINGS (
TOPPING_ID INT NOT NULL,
TOPPING_NAME VARCHAR(255) NOT NULL,
TOPPING_PRICE_CUST FLOAT NOT NULL,
TOPPING_PRICE_BIZ FLOAT NOT NULL,
TOPPING_INV_MIN FLOAT NOT NULL,
TOPPING_INV_CURR FLOAT NOT NULL,
TOPPING_DOUBLE INT NOT NULL,
PIZZA_SIZE INT NOT NULL, 
PRIMARY KEY (TOPPING_ID)
);

CREATE TABLE PIZZAS (
PIZZA_ID INT NOT NULL,
PIZZA_SIZE VARCHAR(255) NOT NULL,
FOREIGN KEY (TOPPING_ID)
	REFERENCES TOPPINGS(TOPPING_ID),
PRIMARY KEY (PIZZA_ID)
);

CREATE TABLE ORDERS(
ORDER_ID INT NOT NULL,
ORDER_DATE DATE,
ORDER_TYPE VARCHAR(255),
PRIMARY KEY (ORDER_ID)
);