/*Written by Josh Kennerly and Justin Schulz*/

use Pizzeria;

DROP TABLE IF EXISTS TOPPINGS;

DROP TABLE IF EXISTS PIZZA;

DROP TABLE IF EXISTS ORDERS;

DROP TABLE IF EXISTS CUSTOMER;

DROP TABLE IF EXISTS DINE_IN;

DROP TABLE IF EXISTS TAKEOUT;

DROP TABLE IF EXISTS DELIVERY;

DROP TABLE IF EXISTS DISCOUNTS;

DROP TABLE IF EXISTS BASE_PRICE;

DROP TABLE IF EXISTS TOTAL_TOPS;

DROP TABLE IF EXISTS DISCOUNT_PIZZA;

DROP TABLE IF EXISTS DISCOUNT_ORDER;

DROP TABLE IF EXISTS PIZZA_ORDER;