/*Written by Josh Kennerly and Justin Schulz*/

use Pizzeria;

INSERT INTO DISCOUNTS(DISCOUNT_ID, DISCOUNT_NAME, DISCOUNT_PERCENT, DISCOUNT_CASH) VALUES (1, 'Employee', 15, 0);
INSERT INTO DISCOUNTS(DISCOUNT_ID, DISCOUNT_NAME, DISCOUNT_PERCENT, DISCOUNT_CASH) VALUES (2, 'Lunch Special Medium', 0, 1.00);
INSERT INTO DISCOUNTS(DISCOUNT_ID, DISCOUNT_NAME, DISCOUNT_PERCENT, DISCOUNT_CASH) VALUES (3, 'Lunch Special Large', 0, 2.00);
INSERT INTO DISCOUNTS(DISCOUNT_ID, DISCOUNT_NAME, DISCOUNT_PERCENT, DISCOUNT_CASH) VALUES (4, 'Specialty Pizza', 0, 1.50);
INSERT INTO DISCOUNTS(DISCOUNT_ID, DISCOUNT_NAME, DISCOUNT_PERCENT, DISCOUNT_CASH) VALUES (5, 'Gameday Special', 20, 0);